### ISSUE TITLE
JSON code blocks unreadable

### ISSUE THREAD

**Issue by nickmcm92** [iarlo/NPM-Dark#1]
The Strings are coloured as Navy which is very hard to read with the dark background

Below is the rule setting the colors as Navy.
```css
.markdown .meta.structure.dictionary.json > .string.quoted.double.json, .markdown .meta.structure.dictionary.json > .string.quoted.double.json .punctuation.string {
	color: navy;
}
```

[Sample page with JSON code block](https://www.npmjs.com/package/express-validation#errors)
